### ISSUE TITLE
Service "ovh" not found

### ISSUE THREAD

**Issue by Kraddle** [coopTilleuls/CoopTilleulsOvhBundle#12]
HI,
Thanks for your work. 😀
the  'ovh' service call does not work on Symfony 4.1.1.
`$this->get('ovh')`
I get this error : Service "ovh" not found: even though it exists in the app's container

but using the dependency  injection
`use Ovh\Api;`
it's works

**Comment by dunglas** [comment]
Fixed in https://github.com/coopTilleuls/CoopTilleulsOvhBundle/commit/0e8d0037696a8274c5b94b6fabaab54f5ac7e524

Thanks for reporting

**Comment by Kraddle** [comment]
No problem 😉
