### ISSUE TITLE
Available with Symfony 3.1.*

### ISSUE THREAD

**Issue by florianhenonin** [coopTilleuls/CoopTilleulsOvhBundle#6]
I have an error when I'm trying to install the bundle with composer require tilleuls/ovh-bundle
Is Symfony 3.1.* supported ?

`  Problem 1
    - Installation request for tilleuls/ovh-bundle ^1.0 -> satisfiable by tilleuls/ovh-bundle[v1.0.0].
    - Conclusion: remove symfony/symfony v3.1.8
    - Conclusion: don't install symfony/symfony v3.1.8
    - tilleuls/ovh-bundle v1.0.0 requires symfony/http-kernel ~2.3 -> satisfiable by symfony/http-kernel[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - don't install symfony/http-kernel v2.4.0|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.4.1|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.4.10|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.4.2|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.4.3|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.4.4|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.4.5|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.4.6|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.4.7|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.4.8|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.4.9|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.5.0|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.5.1|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.5.10|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.5.11|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.5.12|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.5.2|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.5.3|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.5.4|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.5.5|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.5.6|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.5.7|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.5.8|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.5.9|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.6.0|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.6.1|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.6.10|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.6.11|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.6.12|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.6.13|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.6.2|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.6.3|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.6.4|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.6.5|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.6.6|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.6.7|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.6.8|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.6.9|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.0|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.1|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.10|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.11|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.12|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.13|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.14|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.15|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.16|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.17|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.18|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.19|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.2|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.20|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.21|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.22|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.23|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.3|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.4|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.5|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.6|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.7|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.8|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.7.9|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.0|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.1|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.10|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.11|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.12|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.13|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.14|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.15|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.16|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.2|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.3|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.4|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.5|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.6|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.7|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.8|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.8.9|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.0|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.1|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.10|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.11|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.12|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.13|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.14|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.15|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.16|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.17|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.18|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.19|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.2|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.20|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.21|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.22|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.23|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.24|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.25|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.26|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.27|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.28|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.29|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.3|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.30|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.31|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.32|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.33|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.34|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.35|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.36|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.37|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.38|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.39|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.4|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.40|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.41|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.42|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.5|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.6|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.7|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.8|don't install symfony/symfony v3.1.8
    - don't install symfony/http-kernel v2.3.9|don't install symfony/symfony v3.1.8
    - Installation request for symfony/symfony (locked at v3.1.8, required as 3.1.*) -> satisfiable by symfony/symfony[v3.1.8].
`

**Comment by dunglas** [comment]
Can you try to install the `dev-master` version please? If you confirm it works we'll tag a new version.

**Comment by florianhenonin** [comment]
It works.
Thanks for your work, you can tag the version.

**Comment by dunglas** [comment]
Done: https://github.com/coopTilleuls/CoopTilleulsOvhBundle/releases/tag/v1.0.1
